version: "3.3"

services:
  webserver:
    build: 
      context: ./docker-easyphp
    container_name: 'webserver'
    restart: 'always'
    ports:
      - "80:80"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
  mysql:
    build: ./docker-mariadb
    container_name: 'mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: itop
      MYSQL_USER: itop
      MYSQL_PASSWORD: itop
